#!/bin/sh

# `prepare-commit-msg`
#
# This hook prepends commit messages with a numerical tag when
# committing under numbered branches.
#
# For example:
#
#   feature/8932-callout-links -> "[#8932] ..."
#   ticket-39451 -> "[#39451] ..."
#   release/1.2.3 -> "[v1.2.3] ..."
#
# To use this script, place it in the '.git/hooks' directory of your
# repository. You may prefer to add it to your global git templates
# and use 'git init' instead. See `git help init` and `git help hooks`
# for instructions.

_current_branch()
{
    git branch 2>/dev/null | grep -e '^* ' | sed -e 's/* \(.*\)/\1/'
}

_branch_is_numbered()
{
    echo "$1" | grep -q -e '^.*[[:alnum:][:punct:]]\+[/-][0-9.]\+.*$'
}

_branch_is_typed()
{
    echo "$1" | grep -q -e '^.\+/[[:alnum:][:punct:]]\+.*$'
}

_branch_type_prefix()
{
    TYPE=$(
        echo "$1" | sed -e 's/^\([[:alnum:][:punct:]]\+\)[\/-][0-9.]\+.*/\1/'
    )

    if [ "$TYPE" = "release" ]; then
        echo $(eval "echo `git config --get gitflow.prefix.versiontag`")
    elif [ -n "$TYPE" ]; then
        echo "#"
    fi
}

_branch_number()
{
    echo "$1" | sed -e 's/^.*[[:alnum:][:punct:]]\+[\/-]\([0-9.]\+\).*/\1/'
}

_branch_number_label()
{
    BRANCH="$1"
    PREFIX=$(_branch_type_prefix "$BRANCH")
    NUMBER=$(_branch_number "$BRANCH")

    [ -n "${NUMBER}" ] && echo "[${PREFIX}${NUMBER}]"
}

_branch_name_label()
{
    NAME=$(
        echo "$1" | sed -e 's/^.*[[:alnum:][:punct:]]\+\/\([[:alnum:][:punct:]]\+\).*/\1/'
    )
    [ -n "${NAME}" ] && echo "[${NAME}]"
}

_commit_is_merge()
{
    [ "merge" = "$1" ]
    return $?
}

_merge_branch_label()
{
    LABEL=""
    MESSAGE=$(cat)
    SOURCE_BRANCH=$(echo $MESSAGE | sed -e "s/.*branch '\(.\+\)' .*/\1/")
    TARGET_BRANCH=$(echo $MESSAGE | sed -e "s/.*into \([[:alnum:][:punct:]\/-]\+\).*/\1/")

    if _branch_is_numbered "$TARGET_BRANCH"; then
        LABEL=$(_branch_number_label "$TARGET_BRANCH")
    elif _branch_is_typed "$TARGET_BRANCH"; then
        LABEL=$(_branch_name_label "$TARGET_BRANCH")
    fi

    TAG=""

    if _branch_is_numbered "$SOURCE_BRANCH"; then
        TAG=$(_branch_number_label "$SOURCE_BRANCH")
    elif _branch_is_typed "$SOURCE_BRANCH"; then
        TAG=$(_branch_name_label "$SOURCE_BRANCH")
    elif [ -n "LABEL" ]; then
        TAG=" ${SOURCE_BRANCH}:"
    else
        TAG="${SOURCE_BRANCH}:"
    fi

    [ -n "$TAG" ] && LABEL="${LABEL}${TAG}"

    [ -n "$LABEL" ] && echo "$LABEL"
}

LABEL=

if _commit_is_merge "$2"; then
    LABEL=$(_merge_branch_label < "$1")
elif _branch_is_numbered "$(_current_branch)"; then
    LABEL=$(_branch_number_label "$(_current_branch)")
elif _branch_is_typed "$(_current_branch)"; then
    LABEL=$(_branch_name_label "$(_current_branch)")
fi

if [ -n "$LABEL" ] && ! grep -q "^\\${LABEL}" "$1"; then
    echo "$LABEL $(cat $1)" > "$1"
fi

exit 0;
