#!/bin/sh

# `prepare-commit-msg`
#
# This hook prepends commit messages with a numerical tag when
# committing under numbered branches.
#
# For example:
#
#   feature/8932-callout-links -> "[#8932] ..."
#   ticket-39451 -> "[#39451] ..."
#
# To use this script, place it in the '.git/hooks' directory of your
# repository. You may prefer to add it to your global git templates
# and use 'git init' instead. See `git help init` and `git help hooks`
# for instructions.

_current_branch()
{
    git branch 2>/dev/null \
        | grep -e '^* ' \
        | sed -e 's/* \(.*\)/\1/'
}

_branch_is_ticket()
{
    _current_branch \
        | grep -q -e '^[[:alnum:][:punct:]]\+[/-][0-9]\+.*$'
}

_branch_ticket_number()
{
    _current_branch \
        | grep -e '^[[:alnum:][:punct:]]\+[/-][0-9]\+.*$' \
        | sed -e 's/^[[:alnum:][:punct:]]\+[\/-]\([0-9]\{1,\}\).*/\1/'
}

if _branch_is_ticket
then
    TICKET=$(_branch_ticket_number)
    [ -n "$TICKET" ] && echo "[#$TICKET] $(cat $1)" > "$1"
fi

exit 0;
